[versions]
agp = "8.13.0"
kotlin = "2.2.20"
coreKtx = "1.16.0"
activity = "1.10.1"
webkit = "1.14.0"
playServicesAds = "25.5.0"
ump = "4.0.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
androidx-webkit = { group = "androidx.webkit", name = "webkit", version.ref = "webkit" }
play-services-ads = { group = "com.google.android.gms", name = "play-services-ads", version.ref = "playServicesAds" }
user-messaging-platform = { group = "com.google.android.ump", name = "user-messaging-platform", version.ref = "ump" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
